version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wvs
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  awvs:
    image: akkuman/awvs:v15.5
    ports:
      - 13443:3443
    environment:
      acunetix_user: test@admin.com
      acunetix_password: Test1*1
      acunetix_database: postgresql://postgres:postgres@db:5432/wvs
      acunetix_token: 672f976f9f1a8e8d8742d5ccf7314c15
